- name: Rotate Local Firewall Account Password
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    target_username: 'padmin'
    new_password: '!Asx12Drfv23asWEQf!'

  collections:
      - paloaltonetworks.panos

  pre_tasks:
    - name: Read Credentials From Vault
      include_vars: 'firewall-secrets.yml'
      no_log: 'yes'

  tasks:

    - name: Set New Password for Account
      panos_administrator:
          provider: '{{ provider }}'
          admin_username: '{{ target_username }}'
          admin_password: '{{ new_password }}'
          superuser: true
          commit: false
      register: result







